@baseUrl = http://localhost:3000
@customer_code = 123456

### Teste de Upload da Imagem
POST {{baseUrl}}/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="customer_code"

{{customer_code}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="measure_datetime"

2024-08-29T10:30:00Z
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="measure_type"

WATER
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="base64.txt"
Content-Type: text/plain

< ./mock/base64.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### GET - List Measures
GET {{baseUrl}}/test/list?measure_type=array
### GET - List Measures
GET {{baseUrl}}/{{customer_code}}/list?measure_type=gas
### GET - List Measures
GET {{baseUrl}}/test/list

### PATCH
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "measure_uuid": "71bcf1c5-6623-4521-bc20-86a7b896a2ab",
  "confirmed_value": 23
}

### PATCH
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "measure_uuid": "asset2",
  "confirmed_value": 23.5
}

### PATCH
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "measure_uuid": "asset2",
  "confirmed_value": "A1"
}

### PATCH
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "image": "asset2",
  "customer_code": "A1"
}

