@baseUrl = http://localhost:3000

### GET
GET {{baseUrl}}/healthApi

### POST
POST {{baseUrl}}/upload
Content-Type: application/json

{
  "image": "asset2",
  "customer_code": "A1",
  "measure_datetime": "1724887714",
  "measure_type": "GAS"
}

### GET - List Measures
GET {{baseUrl}}/test/list?measure_type=array
### GET - List Measures
GET {{baseUrl}}/test/list?measure_type=gas
### GET - List Measures
GET {{baseUrl}}/test/list

### PATCH
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "measure_uuid": "asset2",
  "confirmed_value": 23
}

### PATCH
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "measure_uuid": "asset2",
  "confirmed_value": 23.5
}

### PATCH
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "measure_uuid": "asset2",
  "confirmed_value": "A1"
}

### PATCH
PATCH {{baseUrl}}/confirm
Content-Type: application/json

{
  "image": "asset2",
  "customer_code": "A1"
}

